# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomePage(object):
    def setupUi(self, WelcomePage):
        WelcomePage.setObjectName("WelcomePage")
        WelcomePage.resize(800, 600)
        self.label = QtWidgets.QLabel(WelcomePage)
        self.label.setGeometry(QtCore.QRect(200, 100, 400, 80))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(72)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {text-color: rgb(34, 67, 195)};")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(WelcomePage)
        QtCore.QMetaObject.connectSlotsByName(WelcomePage)

    def retranslateUi(self, WelcomePage):
        _translate = QtCore.QCoreApplication.translate
        WelcomePage.setWindowTitle(_translate("WelcomePage", "Form"))
        self.label.setText(_translate("WelcomePage", "Welcome"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomePage = QtWidgets.QWidget()
    ui = Ui_WelcomePage()
    ui.setupUi(WelcomePage)
    WelcomePage.show()
    sys.exit(app.exec_())
